create table if not exists public.check_states (
  id bigint generated by default as identity primary key,
  page_slug text not null,
  item_id text not null,
  purchase boolean not null default false,
  prepare boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint check_states_page_slug_item_id_key unique (page_slug, item_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_check_states_updated_at on public.check_states;
create trigger set_check_states_updated_at
before update on public.check_states
for each row
execute function public.set_updated_at();

alter table public.check_states enable row level security;

drop policy if exists "anon can read check states" on public.check_states;
create policy "anon can read check states"
on public.check_states
for select
to anon
using (true);

drop policy if exists "anon can insert check states" on public.check_states;
create policy "anon can insert check states"
on public.check_states
for insert
to anon
with check (true);

drop policy if exists "anon can update check states" on public.check_states;
create policy "anon can update check states"
on public.check_states
for update
to anon
using (true)
with check (true);

drop policy if exists "anon can delete check states" on public.check_states;
create policy "anon can delete check states"
on public.check_states
for delete
to anon
using (true);
